const ACTIONS = {
  SET_CURRENT_PLAY_AREA: 'SET_CURRENT_PLAY_AREA',
  OPEN_QR: 'OPEN_QR',
  CLOSE_MODAL: 'CLOSE_MODAL',
  // API Actions
  UPDATE_USER_DATA: 'UPDATE_USER_DATA',
  UPDATE_TEAM_DATA: 'UPDATE_TEAM_DATA',
  // Page Loader State
  UPDATE_USER_PAGE_LOADING_STATUS: 'UDPATE_USER_PAGE_LOADING_STATUS',
  UPDATE_TEAMWIDGET_LOADING_STATUS: 'UPDATE_TEAMWIDGET_LOADING_STATUS',
  UPDATE_RANKING_DATA: 'UPDATE_RANKING_DATA'
};

export { ACTIONS };