const NEW_MATCH_ACTIONS = {
  UPDATE_ALL_TEAMS_DATA: 'UPDATE_ALL_TEAMS_DATA',
  SELECT_HOME_TEAM: 'SELECT_HOME_TEAM',
  SELECT_AWAY_TEAM: 'SELECT_AWAY_TEAM',
  SELECT_RESULT: 'SELECT_RESULT',
  SUBMIT_FORM: 'SUBMIT_FORM',
}

export { NEW_MATCH_ACTIONS }